= Vision: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Systems {project-system-name} überblicksartig zu beschreiben. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie das System {project-system-name} diese Bedarfe erfüllt, werden durch User Stories im Product Backlog sowie dem UX-Konzept beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System {project-system-name}, das von Cocktails-Systems entwickelt wird. Das System wird es Privatkunden erlauben, individuale Cocktails zu erstellen und den Versand zu verwenden, um damit bequem von zuhause Cocktails zu genießen.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.
//Siehe <<./glossary.adoc#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.
Im Moment ist es nicht möglich Cocktails für zuhause oder private Veranstaltungen zu bestellen. Dies sehen wir als Opportunity auf diese Kunden mit genussvollen Cocktails zu beliefern und damit unseren Kundenkreis zu erweitern.

=== Produktvision
//Eine Produktvision beschreibt das Einsatzziel der Anwendung und sorgt für ein gemeinsames Ziel und Verständnis für alle Beteiligten im Projekt. Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
| Für | Privatkunden
| der / die | Cocktails zuhause genießen wollen
| ist das  | Online-Bestellsystem {project-system-name}
| eine  | Webanwendung
| der / die | Individualität unserer Bar wiederspiegelt
| anders als | bei stationäre Bars
| kann unser Produkt | auch geliefert werden
|===


//Beispiel
//[cols="1,3"]
//|===
//| Für | Studierende der HTWD
//| die | zu wenig Zeit in der Mittagspause zum Essen haben
//| ist   | Flying Burger
//| ein  | Lieferdient für Burger
//| der  | per Drohne liefert
//| anders als | landgestützte Lieferdienste
//| kann unser Produkt |  durchs Fenster direkt in den Hörsaal liefern.
//|===

== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| Barbesitzer (Auftraggeber)
| Geschäftsfeld erweitern auf Privatkunden
| Lieferant für die Cocktails und für die Aktuellhaltung der Daten auf der Website

| Besteller der Cocktails
| Möchte die selben Cocktails wie in der Bar schnell geliefert haben
| Nutzung des Systems

| Gesetzgeber
| Möchte das gesetzliche Vorgaben von Lebensmittelsicherheit, Datenschutz und Jugendschutz einhalten werden
| Im System muss ein Nachweis / ein Beschränkung für die Einhaltung der vorher genannten Gesetze bestehen

| Entwickler
| einfach zu bedienendes System
| Programmieren, warten und Testen das System

|===

Die Verfeinerung der Stakeholder, die das System benutzen, wird im UX-Konzept mittels Personas vorgenommen.


== Produktüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features / Funktionen | Geplantes Release
| xx | xx | xx | xx
|===


=== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die Qualitätsanforderungen an das geplante Produkt beschreiben.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen.
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===
